version: "3"

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MySecr3tPassWordas2
      - POSTGRES_DB=DjangoDB

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
volumes:
  postgres-db:
    external: false
